version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5
    executor: ruby/default
    steps:
      - checkout
      # Install gems with Bundler
      - ruby/install-deps:
          # Need to clear the gem cache? Set or bump the CACHE_VERSION in your
          # CircleCi project: Project Settings > Environment Variables
          key: searchgov_style-{{ .Environment.CACHE_VERSION }}-{{checksum "Gemfile.lock" }}
      - run:
          name: Rubocop
          # CodeClimate will also run Rubocop, but only on PRs.
          # Running Rubocop in CircleCI allows us to see failures earlier
          command: bundle exec rubocop
      - run:
          name: Build Gem
          # Ensure the gem can be successfully built
          command: bundle exec rake build
