version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5
    executor: ruby/default
    steps:
      - checkout

      # Install gems with Bundler
      - ruby/install-deps
          # Workaround for Bundler not using gem cache
          # https://github.com/CircleCI-Public/ruby-orb/pull/77
          path: /home/circleci/.rubygems

      - run:
          name: Rubocop
          # CodeClimate will also run Rubocop, but only on PRs.
          # Running Rubocop in CircleCI allows us to see failures earlier
          command: bundle exec rubocop

      - run:
          name: Build Gem
          # Ensure the gem can be successfully built
          command: bundle exec rake build
